---
# This play is for blacklist devices
- name: Check that the multipath.conf exists
  stat:
    path: /etc/multipath.conf
  register: file_exist

- name: Ensure that multipathd services is enabled if not
  shell: vdsm-tool configure --module multipath
  when: file_exist.stat.exists == False

- name: Ensure that multipathd services is running
  service:
    name: multipathd
    state: started
    enabled: yes

- name: Create /etc/multipath/conf.d if doesn't exists
  file:
    path: /etc/multipath/conf.d
    recurse: yes
    state: directory

- name: Get the UUID of the devices
  ignore_errors: True
  shell: multipath -a /dev/{% if item.startswith('sd') %}{{ item | regex_replace('[0-9]+$') }}{% else %}{{ item }}{% endif %}
  register: dev_uuid
  with_items: "{{ blacklist_mpath_devices }}"

- name: Remove UUID of the devices from /etc/multipath/wwids
  ignore_errors: True
  shell: multipath -w {{ item.stdout.split()[1][1:-1] }}
  loop: "{{ dev_uuid.results }}"
  when: blacklist_mpath_devices | length > 0 and item.failed == false

- name: Add entry in system.service
  ignore_errors: True
  command: lvmdevices --adddev /dev/{{ item }}
  with_items: "{{ blacklist_mpath_devices }}"
  when: blacklist_mpath_devices | length > 0

- name: Clean device
  ignore_errors: True
  command: wipefs -a /dev/{{ item }}
  with_items: "{{ blacklist_mpath_devices }}"
  when: blacklist_mpath_devices | length > 0

- name: Check that the blacklist.conf exists
  stat:
    path: /etc/multipath/conf.d/blacklist.conf
  register: stat_result

- name: Create blacklist template content
  blockinfile:
    path: /etc/multipath/conf.d/blacklist.conf
    create: yes
    state: present
    block: |
      blacklist {
      }
  when: stat_result.stat.exists == False

- name: Add wwid to blacklist in blacklist.conf file
  blockinfile:
    path: /etc/multipath/conf.d/blacklist.conf
    insertafter: 'blacklist'
    block: |
       wwid "{{ item.stdout.split()[1][1:-1] }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.item }}"
  loop: "{{ dev_uuid.results }}"
  when: blacklist_mpath_devices | length > 0 and item.failed == false

- name: Reload multipathd
  shell: systemctl reload multipathd

  tags:
    - cleanup_bricks
